extends Node

enum {
	# OPTIONS
	IS_PRODUCTION_BUILD, 
	
	# GRAPHICS
	START_AT_FULLSCREEN,	
	
	# AUDIO
	AUDIO_MUTE,
	
	# PROGRESS
	DEBUG_STORY_PROGRESS,
	DEBUG_USER_PROFILE_REF,
	DEBUG_STORY_PROGRESS_VAL,
	DEBUG_CURRENT_STORY_VAL,
	
	# OS
	SKIP_SPLASH, 
	SKIP_INTRO, 
	SKIP_OFFICE_INTRO,
	
	# INTRO
	INTRO_SKIP_LOGO, INTRO_SKIP_TITLE, INTRO_SKIP_SEQUENCE, INTRO_SKIP_STARTAT,
	
	# SAVE FILES
	NEW_PROGRESS_FILE, NEW_SYSTEM_FILE, NEW_PERSISTANT_FILE, NEW_QUICKSAVE_FILE,
	
	# OS
	OS_SKIP_BOOT, OS_SKIP_TO_GAME, OS_APP_FAST_LOAD,
	
	# APP
	APP_SKIP_LOADING_SCREEN, APP_SKIP_TITLESCREEN, 
	
	# GAMEPLAY
	GAMEPLAY_SKIP_SETUP_PROGRSS, GAMEPLAY_START_AT_RING_LEVEL, 
	GAMEPLAY_ENABLE_SCP_DEBUG,
	GAMEPLAY_SKIP_OBJECTIVES, GAMEPLAY_MAX_ENERGY, 
	GAMEPLAY_ALL_PERSONNEL,
	
	# RESEARCHER
	STAFF_DEBUG,
	STAFF_XP_REQUIRED_FOR_PROMOTION,
	STAFF_STARTING_RESEARCHERS,
	STAFF_STARTING_ADMIN,
	STAFF_STARTING_SECURITY,
	STAFF_STARTING_DCLASS,
}



var refs:Dictionary = {}

func assign(key:int, val) -> void:
	refs[key] = val

func get_val(key:int):
	if refs[IS_PRODUCTION_BUILD]:
		if refs[key] is bool:
			return false	
	return refs[key]
