extends Node

enum {
	NEXT, BACK, SKIP, DONE, 
	HIRE_LEAD, HIRE_SUPPORT, 
	PURCHASE_RD_ITEM, PURCHASE_BUILD_ITEM, PURCHASE_BASE_ITEM,
	PURCHASE_TIER,
	CONTAIN_START, CONTAIN_REJECT,
	TRANSFER_SCP_TO_NEW_LOCATION
}

enum {
	BUILD_ITEM, 
	RESEARCH_ITEM, 
	BASE_ITEM, 
	RECRUIT,
	INITIAL_CONTAINMENT,
	CONTAIN_TRANSFER_CANCEL,
	CANCEL_TRANSFER_SCP_TO_NEW_LOCATION
}

enum EVENTS {
	PROMPT
}
