extends Node

enum TYPE {
	BASE_IS_SETUP, 
	
	ENABLE_NEXT,
	ENABLE_DESTROY_ROOM,
	ENABLE_ACTIVE_ABILITY_SHORTCUTS, ENABLE_PASSIVE_ABILITY_SHORTCUTS,
	ENABLE_INVESTIGATE, 
	ENABLE_OBJECTIVES_BTN, 
	ENABLE_SAVE_AND_LOAD,
	
	# -----  UI
	UI_ENABLE_NAMETAGS,
	UI_ENABLE_ABILITY_HINTS,
	
	# -----
	ENABLE_ACTION_DETAILS, ENABLE_ACTIONS_RESEARCHER, ENABLE_ACTIONS_SCP, 
	ENABLE_ROOM_DETAILS_BTN, ENABLE_DATABASE_BTN,
	# ----
	ENABLE_UPGRADES,
	# -----
	UPGRADE_LEVEL, AP_ROOM_LIMIT
}
