extends Node

enum TYPE {
	DISMISS_RESEARCHER, 
	SITEWIDE_BROWNOUT, 
	IN_DEBT_WARNING
}

enum DISMISS_TYPE {THANK_AND_DISMISS, ADMINISTER_AMNESTICS, TERMINATE}
enum BROWNOUT_OPTIONS { EMERGENCY_GENERATORS, DO_NOTHING }
enum IN_DEBT_OPTIONS { EMERGENCY_FUNDS, DO_NOTHING }
