extends Node

enum TYPE {
	GAME_OVER,
	DISMISS_RESEARCHER, 
	SITEWIDE_BROWNOUT, 
	IN_DEBT_WARNING,
	MORALE, 
	SAFETY, 
	READINESS,
	HIRE_RESEARCHER,
	CLONE_RESEARCHER,
	PROMOTE_RESEARCHER
}

enum DISMISS_TYPE {THANK_AND_DISMISS, ADMINISTER_AMNESTICS, TERMINATE}
enum BROWNOUT_OPTIONS { EMERGENCY_GENERATORS, DO_NOTHING }
enum IN_DEBT_OPTIONS { EMERGENCY_FUNDS, DO_NOTHING }
enum GAME_OVER_OPTIONS { RESTART }
