extends Node

enum {
	GAMEPLAY_LOOP, OS_ROOT, OS_LAYOUT, STRUCTURE_3D, RENDERING,
	ROOM_NODES, INFO_CONTAINER, TIMELINE, FLOOR_INFO, 
	ACTION_CONTAINER, ROOM_INFO
}

enum SOURCE {FACILITY, SCPS, TESTING, RESEARCHERS}
