extends Node

enum {
	GAMELAYER_SUBVIEWPORT,
	GAMEPLAY_LOOP, OS_ROOT, OS_LAYOUT, STRUCTURE_3D, RENDERING,
	ROOM_NODES, INFO_CONTAINER, TIMELINE, FLOOR_INFO, 
	ACTION_CONTAINER, ROOM_INFO,
	LINE_DRAW, HOTKEY_CONTAINER,
	BTN_CONTROLS,
}

enum SOURCE {FACILITY, SCPS, TESTING, RESEARCHERS}
