extends Node

enum {
	AUDIO,
	MAIN, 
	AUDIO_BG,
	TASKBAR,
	GAMELAYER_SUBVIEWPORT, 
	GAMEPLAY_LOOP, 
	OS_LAYOUT, 
	STRUCTURE_3D, 
	RENDERING,
	GAMEPLAY_HEADER,
	DOOR_SCENE,
	ROOM_NODES, INFO_CONTAINER, TIMELINE, FLOOR_INFO, MARKED_OBJECTIVES,
	ACTION_CONTAINER, ROOM_INFO,
	LINE_DRAW, HOTKEY_CONTAINER,
	BTN_CONTROLS,
	MEDIA_PLAYER,
	ACTIVE_MENU,
}

enum SOURCE {FACILITY, SCPS, TESTING, RESEARCHERS}
