@tool
extends Node

enum TRAITS { 
	HARD_WORKING,
	MOTIVATED, 
	CLEVER,
	STUBBORN
}

enum SYNERGY_TRAITS {
	DREAM_TEAM = TRAITS.CLEVER + TRAITS.MOTIVATED,
	UNRELENTING = TRAITS.MOTIVATED + TRAITS.HARD_WORKING
}


enum SPECALIZATION { ENGINEERING, BIOLOGY, PSYCHOLOGY }
