extends Node

enum CURRENCY { MONEY, SCIENCE, MATERIAL, CORE }

enum PERSONNEL { TECHNICIANS, STAFF, SECURITY, DCLASS  }

enum METRICS { MORALE, SAFETY, READINESS }

#enum TYPE { 
	#MONEY, ENERGY, SCIENCE,
	#TECHNICIANS, STAFF, SECURITY, DCLASS 
#}
