@tool
extends Node

enum REF {
	DEBUG_ROOM,
		
	# -----------------  RECRUITMENT
	PRISONER_BLOCK,
	SECURITY_DEPARTMENT,
	ADMIN_OFFICE,
	ACADEMIC_OUTREACH,
	MTF_BARRICKS,
	
	# -----------------  CONTAINMENT
	STANDARD_CONTAINMENT_CELL,
	
	# -----------------  RESOURCES
	MONEY_GEN_1,			MONEY_GEN_2,
	RESEARCH_GEN_1,		RESEARCH_GEN_2,
	MATERIAL_GEN_1,		MATERIAL_GEN_2,
	CORE_GEN_1,			CORE_GEN_2,
	MONEY_CONVERTER,
	
	
	# -----------------  UTILITY
	UI_ASSIST,
	WEAPONS_RANGE,
	SCRANTON_REALITY_ANCHOR,
	HP_CLINIC, 
	SP_CLINIC,	
	STAFF_ROOM,
	CAFETERIA,
	
	# -----------------  ENERGY
	ENERGY_STORAGE, ENERGY_SYPHON,
	
	# -----------------  SPECIALS
	DIRECTORS_OFFICE, HQ,
	
	HR_DEPARTMENT, OPERATIONS_SUPPORT, # BATCH 1
	MINIERAL_MINING, GEOTHERMAL_POWER, # BATCH 2
	
	GENERATOR_SUBSTATION,
	PROBABILITY_ROOM, 
	CHRONO_ROOM, 
	NUCLEAR_FAILSAFE,	
	
}


enum EMERGENCY_MODES { 
	NORMAL, 
	CAUTION, 
	WARNING, 
	DANGER 
}

enum CATEGORY {
	CONTAINMENT, 
	RECRUITMENT,
	RESOURCES,
	ENERGY,
	UTILITY,
	SPECIAL
}
