enum TYPE {
	BIN, CLEAR, 
	DELETE, DOT, DOWNLOAD, EMAIL, EXE_FILE, TXT_FILE,
	MEDIA_FORWARD, MEDIA_PAUSE, MEDIA_PLAY, MINUS, MUSIC, 
	NEW, PLUS, SETTINGS, STOP, 
	THINKING, LOADING, SAVE, CAUTION, WARNING, HOURGLASS, INFO,
	
	BUILD, RECRUIT, ASSIGN, NEXT, BACK,
	CONTAIN, INVESTIGATE,
	MONEY, ENERGY, D_CLASS, DRS, STAFF, SECURITY, 
	ARROW_DOWN, ARROW_UP,
	
	GLOBAL, RING, 
	
	TARGET, NO_ISSUES, DANGER, RESEARCH,
	CAMERA_A, CAMERA_B, DOWN_ARROW,
	LOCK, UNLOCK, CHECKBOX, EMPTY_CHECKBOX,
	QUESTION_MARK, CONVERSATION,
	NO_ELECTRICITY, UP_ARROW, SWAP,
	
	ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE,
	DESKTOP,
	FROZEN,	
	LAYER, LAYERS, 
	OS_CURRENCY,
	NONE,
}
