extends Node

enum TYPE {
	BIN, CLEAR, 
	DELETE, DOT, DOWNLOAD, EMAIL, EXE_FILE, TXT_FILE,
	MEDIA_FORWARD, MEDIA_PAUSE, MEDIA_PLAY, MINUS, MUSIC, 
	NEW, PLUS, SETTINGS, STOP, 
	THINKING, LOADING, SAVE, CAUTION, WARNING, HOURGLASS, INFO,
	
	NONE,
}
